### ISSUE TITLE
hauling.csv is empty

### ISSUE THREAD

**Issue by GnubiBORED** [evetools-dev/eve_tools#15]
after giving scoup permissions hauling.csv is empty running the example.py 
https://github.com/evetools-dev/eve_tools/blob/master/examples.py

Jita Sell | F9- Sell | typeName | packagedVolume | volume_seven_days | volume_thirty_days | type_id | Profit(m) | Profit Margin
-- | -- | -- | -- | -- | -- | -- | -- | --

csv looks like this after running it 

Im inputting structure like this, is this right?
`   to_structure: str = "F9-FUV - ICS Procropolis",`

**Comment by evetools-dev** [comment]
``to_structure`` is correct. Can you provide more info on how you called ``hauling()``? Also, could you verify that ``get_structure_market(to_structure, cname)`` is not empty.

**Comment by Haannbboo** [comment]
Closed as this error can not be reproduced.
