### ISSUE TITLE
ESI.request family docstring hint missing

### ISSUE THREAD

**Issue by evetools-dev** [evetools-dev/eve_tools#6]
With VS Code, code hint for ESI.get() and ESI.head() is 
```Python
(*args: Any, **kwd: Any) -> Coroutine
```
which is supposed to be 
```Python
(key: str, async_loop: List | None = None, **kwd: Any) -> (dict | List[dict])
```
``ESI.get.__doc__`` gives correct docstring.

**Comment by evetools-dev** [comment]
Similar issue occur with ``eve_tools.api.market`` apis.

**Comment by Haannbboo** [comment]
After investigating the issue, all decorators are wrapped with functools.wraps, and ``ESI.get.__annotations__``, ``ESI.get.__doc__``, and ``inspect.signature(ESI.get)`` are correct (same for eve_tools.api.market). When using Pytho IDLE 3.9, the docstring hint is correct. Therefore, this is considered an issue specific for VS Code. 

Please comment on this issue if you have any suggestions.
